### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [vadonata/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 2 - Approaches Expectations
* _Comment(s):_ A lot of your slides didn't have a text conclusion, but just had the query and table. That made it hard to judge what you were able to conclude from the data. 
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 3 - Approaches Expectations
* _Comment(s):_ Most people found because of Medium and NYTimes. And, if they came back, it was because of the Facebook ad or email newsletter. 

I see you had a rank 1-5 in your final slide, you just needed to add more text to summarize what you were trying to communicate with the ranking. 

 ### Overall Score: 13/16
Overall, really great job on this project, Vanessa. Your SQL queries and formatting were pretty spot on, it's clear you have a solid grasp of SQL basics. In regards to the feedback, just wish you verbalized a lot more what the various charts you had were communicating, so the conclusion you're drawing is clearly made.

**Comment by vadonata** [comment]
Hi! Thank you for the feedback. I will note it for further projects. Looking back indeed i should have added more textual information aside from just the code and results. I approached it with the tought in mind that the queries and results were more important than answering questions. :)
